language: node_js
cache:
    directories:
        - ~/.npm
node_js:
    - "9"
    - "8"
    - "6"
    - "5"
branches:
    only:
        - master
script:
    - npm test
    - npm run check-coverage
    - npm run lint
